const { h1, h2, h3, p, bullet, code, pageBreak, table, imageParagraph, titlePage, buildDocument, writeDocx } = require("./common");

const children = [
  ...titlePage({
    code: "DOC-02",
    title: "Diagrama de Base de Datos (Modelo Entidad-Relación)",
    subtitle: "SIGEC - Sistema de Información y Gestión de Casos de Embarazo en Niñas y Adolescentes",
  }),

  h1("1. Introducción"),
  p("Este documento describe el modelo de datos del sistema SIGEC, implementado sobre MySQL 8 mediante el ORM Sequelize 6. El modelo está compuesto por 11 entidades principales que cubren cuatro dominios: seguridad y acceso (usuarios y roles), división geográfica y administrativa, registro de casos de embarazo, y trazabilidad/auditoría."),
  p("La definición de las entidades y sus relaciones se origina en los modelos de Sequelize ubicados en backend/models/ y en el archivo de relaciones backend/models/Relations.js, así como en las migraciones aplicadas a la base de datos (carpeta backend/migrations/)."),

  h1("2. Diagrama Entidad-Relación"),
  ...imageParagraph("er_diagram.png", 580, 900, "Figura 1. Modelo Entidad-Relación de la base de datos 'sigec'"),

  pageBreak(),
  h1("3. Descripción de Entidades"),

  h2("3.1 Seguridad y acceso"),
  h3("ROLE"),
  p("Define los roles del sistema (por ejemplo: administrador, departamental, usuario operativo) que determinan los permisos de acceso a cada módulo."),
  table(
    ["Campo", "Tipo", "Descripción"],
    [
      ["id", "INTEGER (PK)", "Identificador único del rol."],
      ["name", "STRING", "Nombre del rol (ej. 'admin', 'departamental', 'usuario')."],
      ["description", "STRING", "Descripción legible del rol."],
    ],
    [25, 25, 50]
  ),
  p(""),
  h3("USER"),
  p("Representa a los usuarios que pueden autenticarse en el sistema. Cada usuario pertenece a un rol que determina sus permisos."),
  table(
    ["Campo", "Tipo", "Descripción"],
    [
      ["id", "INTEGER (PK)", "Identificador único del usuario."],
      ["name", "STRING", "Nombre completo del usuario."],
      ["email", "STRING (único)", "Correo electrónico, utilizado como identificador de inicio de sesión."],
      ["password", "STRING", "Contraseña almacenada con hash (bcrypt)."],
      ["roleId", "INTEGER (FK -> ROLE.id)", "Rol asignado al usuario."],
      ["isActive", "BOOLEAN", "Indica si el usuario puede iniciar sesión (activo/inactivo)."],
    ],
    [25, 30, 45]
  ),

  pageBreak(),
  h2("3.2 División geográfica y administrativa"),
  h3("DEPARTAMENTO"),
  p("Representa los departamentos de Guatemala (división administrativa de primer nivel)."),
  table(["Campo", "Tipo", "Descripción"], [
    ["id", "INTEGER (PK)", "Identificador único."],
    ["nombre", "STRING", "Nombre del departamento."],
  ], [25, 30, 45]),
  p(""),
  h3("MUNICIPIO"),
  p("Representa los municipios, cada uno asociado a un departamento."),
  table(["Campo", "Tipo", "Descripción"], [
    ["id", "INTEGER (PK)", "Identificador único."],
    ["departamento_id", "INTEGER (FK -> DEPARTAMENTO.id)", "Departamento al que pertenece el municipio."],
    ["nombre", "STRING", "Nombre del municipio."],
  ], [25, 30, 45]),
  p(""),
  h3("DEPARTAMENTAL"),
  p("Representa las direcciones departamentales de educación (DIDEDUC), unidades administrativas del MINEDUC encargadas de supervisar los casos dentro de un departamento."),
  table(["Campo", "Tipo", "Descripción"], [
    ["id", "INTEGER (PK)", "Identificador único."],
    ["nombre", "STRING", "Nombre de la departamental (ej. 'Dirección Departamental de Educación de...')."],
    ["departamento_id", "INTEGER (FK -> DEPARTAMENTO.id)", "Departamento al que pertenece la departamental."],
  ], [25, 30, 45]),
  p(""),
  h3("CENTRO_EDUCATIVO"),
  p("Representa los centros educativos donde estudian o estudiaron las niñas registradas."),
  table(["Campo", "Tipo", "Descripción"], [
    ["id", "INTEGER (PK)", "Identificador único."],
    ["codigo_udi", "STRING", "Código único de identificación (UDI) del centro educativo."],
    ["nombre", "STRING", "Nombre del centro educativo."],
    ["direccion", "TEXT", "Dirección física del centro educativo."],
    ["municipio_id", "INTEGER (FK -> MUNICIPIO.id)", "Municipio donde se ubica el centro educativo."],
    ["sector", "STRING", "Sector (oficial, privado, municipal, cooperativa)."],
    ["jornada", "STRING", "Jornada (matutina, vespertina, etc.)."],
    ["area", "STRING", "Área (urbana o rural)."],
  ], [20, 30, 50]),

  pageBreak(),
  h2("3.3 Registro de casos"),
  h3("NINA"),
  p("Representa a la niña o adolescente sobre quien se registra el caso. Es la entidad central del dominio del negocio."),
  table(["Campo", "Tipo", "Descripción"], [
    ["id", "INTEGER (PK)", "Identificador único."],
    ["cui", "STRING (nullable)", "Código Único de Identificación (CUI/DPI), puede ser nulo si la niña no posee documento."],
    ["nombre_completo", "STRING", "Nombre completo de la niña."],
    ["fecha_nacimiento", "DATE", "Fecha de nacimiento."],
    ["edad", "INTEGER", "Edad calculada o registrada al momento del caso."],
    ["direccion", "TEXT", "Dirección de residencia."],
    ["municipio_id", "INTEGER (FK -> MUNICIPIO.id)", "Municipio de residencia."],
    ["pueblo", "STRING", "Pueblo de pertenencia (maya, xinca, garífuna, ladino, etc.), almacenado como texto."],
    ["comunidad_linguistica", "STRING", "Comunidad lingüística, almacenada como texto."],
  ], [22, 30, 48]),
  p(""),
  h3("CASO_EMBARAZO"),
  p("Representa cada caso de embarazo registrado, vinculando a la niña, su ubicación administrativa y los datos de detección y seguimiento."),
  table(["Campo", "Tipo", "Descripción"], [
    ["id", "INTEGER (PK)", "Identificador único."],
    ["numero_caso", "STRING", "Número de caso, generado de forma autoincremental/correlativa."],
    ["nina_id", "INTEGER (FK -> NINA.id)", "Niña asociada al caso."],
    ["carga_archivo_id", "INTEGER (FK -> CARGA_ARCHIVO.id, nullable)", "Carga masiva que originó el registro, si aplica."],
    ["fecha_ingreso", "DATE", "Fecha de ingreso del caso al sistema."],
    ["fecha_primera_consulta", "DATE", "Fecha de la primera consulta médica registrada."],
    ["forma_deteccion", "STRING", "Forma en que se detectó el caso (ej. denuncia, consulta médica, reporte escolar)."],
    ["departamental_id", "INTEGER (FK -> DEPARTAMENTAL.id)", "Departamental responsable del seguimiento."],
    ["no_notificacion", "STRING", "Número de notificación o expediente externo asociado."],
    ["institucion", "STRING", "Institución que reportó o atendió el caso."],
    ["queja", "STRING", "Referencia a queja o denuncia relacionada, si existe."],
    ["estado", "STRING", "Estado de seguimiento del caso (ej. activo, en proceso, cerrado)."],
  ], [22, 32, 46]),
  p(""),
  h3("HISTORIAL_EDUCATIVO"),
  p("Registra la situación educativa de la niña, asociada a un centro educativo, incluyendo su estado y resultado académico."),
  table(["Campo", "Tipo", "Descripción"], [
    ["id", "INTEGER (PK)", "Identificador único."],
    ["nina_id", "INTEGER (FK -> NINA.id)", "Niña a la que corresponde el registro educativo."],
    ["centro_educativo_id", "INTEGER (FK -> CENTRO_EDUCATIVO.id)", "Centro educativo donde estudia o estudió."],
    ["codigo_personal", "STRING", "Código personal del estudiante."],
    ["status_actual", "STRING", "Estado actual (ej. inscrita, retirada, promovida)."],
    ["grado", "STRING", "Grado académico."],
    ["nivel", "STRING", "Nivel educativo (preprimaria, primaria, básico, diversificado)."],
    ["resultado", "STRING", "Resultado del ciclo escolar (ej. aprobado, reprobado, pendiente)."],
    ["anio", "INTEGER", "Año o ciclo escolar al que corresponde el registro."],
  ], [22, 30, 48]),

  pageBreak(),
  h2("3.4 Carga de datos y auditoría"),
  h3("CARGA_ARCHIVO"),
  p("Registra cada operación de carga masiva de datos desde un archivo Excel, incluyendo el resumen de los resultados."),
  table(["Campo", "Tipo", "Descripción"], [
    ["id", "INTEGER (PK)", "Identificador único."],
    ["nombre_archivo", "STRING", "Nombre del archivo Excel cargado."],
    ["total_registros", "INTEGER", "Total de filas procesadas del archivo."],
    ["registros_nuevos", "INTEGER", "Cantidad de registros nuevos creados."],
    ["registros_duplicados", "INTEGER", "Cantidad de registros detectados como duplicados (no creados)."],
    ["fecha_carga", "DATETIME", "Fecha y hora en que se realizó la carga."],
    ["usuario_id", "INTEGER (FK -> USER.id)", "Usuario que ejecutó la carga masiva."],
  ], [22, 25, 53]),
  p(""),
  h3("AUDITORIA"),
  p("Bitácora del sistema. Registra eventos relevantes ejecutados por los usuarios, incluyendo inicio y cierre de sesión, operaciones CRUD sobre casos y usuarios, cargas masivas y descargas de reportes."),
  table(["Campo", "Tipo", "Descripción"], [
    ["id", "INTEGER (PK)", "Identificador único del registro de auditoría."],
    ["usuario_id", "INTEGER (FK -> USER.id, nullable)", "Usuario que ejecutó la acción ('Sistema' si es nulo)."],
    ["accion", "STRING", "Tipo de acción: inicio_sesion, cierre_sesion, crear_caso, actualizar_caso, crear_usuario, actualizar_usuario, activar_usuario, desactivar_usuario, descargar_pdf, descargar_excel, carga_masiva."],
    ["entidad", "STRING", "Entidad afectada por la acción (ej. 'Caso', 'Usuario')."],
    ["entidad_id", "INTEGER (nullable)", "Identificador de la entidad afectada, si aplica."],
    ["descripcion", "TEXT", "Descripción legible del evento."],
    ["createdAt", "DATETIME", "Fecha y hora del evento."],
  ], [22, 30, 48]),

  pageBreak(),
  h1("4. Relaciones entre Entidades"),
  table(
    ["Relación", "Cardinalidad", "Descripción"],
    [
      ["ROLE -> USER", "1 a N", "Un rol puede estar asignado a muchos usuarios."],
      ["USER -> CARGA_ARCHIVO", "1 a N", "Un usuario puede haber ejecutado múltiples cargas masivas."],
      ["USER -> AUDITORIA", "1 a N", "Un usuario puede generar múltiples registros de auditoría."],
      ["DEPARTAMENTO -> MUNICIPIO", "1 a N", "Un departamento agrupa varios municipios."],
      ["DEPARTAMENTO -> DEPARTAMENTAL", "1 a N", "Un departamento puede tener una o varias direcciones departamentales asociadas."],
      ["DEPARTAMENTAL -> CASO_EMBARAZO", "1 a N", "Una departamental supervisa múltiples casos."],
      ["MUNICIPIO -> CENTRO_EDUCATIVO", "1 a N", "Un municipio contiene varios centros educativos."],
      ["MUNICIPIO -> NINA", "1 a N", "Un municipio agrupa a varias niñas registradas por residencia."],
      ["NINA -> CASO_EMBARAZO", "1 a N", "Una niña puede tener uno o varios casos registrados."],
      ["NINA -> HISTORIAL_EDUCATIVO", "1 a N", "Una niña puede tener varios registros de historial educativo (por año/ciclo)."],
      ["CENTRO_EDUCATIVO -> HISTORIAL_EDUCATIVO", "1 a N", "Un centro educativo puede tener historiales educativos de muchas niñas."],
      ["CARGA_ARCHIVO -> CASO_EMBARAZO", "1 a N", "Una carga masiva puede originar múltiples casos."],
    ],
    [35, 15, 50]
  ),

  h1("5. Notas sobre la Evolución del Esquema"),
  p("El esquema de base de datos ha evolucionado mediante migraciones de Sequelize, ubicadas en backend/migrations/. Las migraciones aplicadas son:"),
  bullet("20260514221353-initial-schema.js: creación del esquema inicial con todas las tablas base (roles, usuarios, ubicación geográfica, niñas, casos, historial educativo y cargas de archivo)."),
  bullet("20260608000000-allow-null-cui.js: modifica la tabla NINA para permitir valores nulos en el campo cui, dado que no todas las niñas registradas cuentan con CUI/DPI."),
  bullet("20260608000001-nina-pueblo-comunidad-strings.js: ajusta los campos pueblo y comunidad_linguistica de la tabla NINA para almacenarse como cadenas de texto libres."),
  bullet("20260610000000-create-auditorias.js: crea la tabla AUDITORIA para el registro de la bitácora del sistema, incluyendo el seguimiento de inicio y cierre de sesión de los usuarios."),
];

writeDocx(buildDocument({ code: "DOC-02", title: "Diagrama de Base de Datos (Modelo Entidad-Relación)", children }), "02_Diagrama_Base_Datos_ER_SIGEC.docx");
