const { h1, h2, h3, p, bullet, code, pageBreak, table, imageParagraph, titlePage, buildDocument, writeDocx } = require("./common");

const children = [
  ...titlePage({
    code: "DOC-03",
    title: "Diagramas de Flujo y Procesos",
    subtitle: "SIGEC - Sistema de Información y Gestión de Casos de Embarazo en Niñas y Adolescentes",
  }),

  h1("1. Introducción"),
  p("Este documento describe los procesos operativos más relevantes del sistema SIGEC mediante diagramas de flujo y secuencia. Cada proceso se presenta junto con una descripción textual de los pasos, los actores involucrados, las validaciones aplicadas y los registros de auditoría generados."),
  p("Los procesos documentados son:"),
  bullet("Inicio y cierre de sesión (autenticación)."),
  bullet("Registro de un nuevo caso de embarazo."),
  bullet("Carga masiva de casos desde un archivo Excel."),
  bullet("Seguimiento y actualización del estado de un caso."),
  bullet("Consulta y exportación de la bitácora de auditoría."),

  pageBreak(),
  h1("2. Proceso: Inicio y Cierre de Sesión"),
  p("Este proceso cubre la autenticación de usuarios mediante JWT (JSON Web Token), la validación del token en peticiones posteriores y el registro de los eventos de inicio y cierre de sesión en la bitácora de auditoría."),
  ...imageParagraph("flow_login.png", 480, 800, "Figura 1. Secuencia de inicio de sesión, validación de token y cierre de sesión"),
  h3("2.1 Pasos del proceso"),
  bullet("1. El usuario ingresa su correo electrónico y contraseña en la vista de Login."),
  bullet("2. El frontend envía POST /api/v1/auth/login con las credenciales."),
  bullet("3. El backend busca al usuario por correo electrónico y compara la contraseña usando bcrypt."),
  bullet("4. Si las credenciales son válidas: se registra un evento de auditoría con acción 'inicio_sesion', se genera un JWT firmado y se responde con el token y los datos del usuario."),
  bullet("5. Si las credenciales son inválidas, se responde con error 401 (No autorizado)."),
  bullet("6. El frontend almacena el token (Pinia + localStorage) y redirige al Dashboard."),
  bullet("7. En cada petición posterior, el middleware verifyToken valida la firma y expiración del JWT; si es válido, attachUser adjunta el usuario a la petición y, si la ruta lo requiere, requireRole valida el rol."),
  bullet("8. Si el token es inválido o expiró, la API responde 401/403, el frontend limpia la sesión y redirige al Login."),
  bullet("9. Al cerrar sesión, el frontend envía POST /api/v1/auth/logout, el backend registra un evento de auditoría con acción 'cierre_sesion', y el frontend limpia el token y el estado local."),

  pageBreak(),
  h1("3. Proceso: Registro de un Nuevo Caso"),
  p("Este proceso describe cómo un usuario autorizado registra un nuevo caso de embarazo en el sistema, incluyendo la creación o reutilización del registro de la niña asociada."),
  ...imageParagraph("flow_registro_caso.png", 280, 850, "Figura 2. Flujo de registro de un nuevo caso"),
  h3("3.1 Pasos del proceso"),
  bullet("1. El usuario autenticado accede a la vista de Registro de Caso y completa el formulario: datos de la niña, fechas (ingreso y primera consulta), forma de detección, institución, departamental responsable, etc."),
  bullet("2. El frontend valida que los campos obligatorios estén completos antes de enviar la solicitud."),
  bullet("3. Se envía POST /api/v1/caso con los datos del formulario."),
  bullet("4. El middleware verifyToken y attachUser validan la sesión del usuario."),
  bullet("5. CasoController.RegistrarCaso verifica si la niña ya existe en la base de datos (por CUI). Si no existe, se crea un nuevo registro en la entidad NINA; si existe, se reutiliza el registro existente."),
  bullet("6. Se crea el registro en CASO_EMBARAZO, asociado a la niña, generando un número de caso correlativo."),
  bullet("7. Se registra un evento de auditoría con acción 'crear_caso'."),
  bullet("8. La API responde 201 (Created) con los datos del caso creado."),
  bullet("9. El frontend actualiza la tabla de casos y los gráficos del dashboard."),

  pageBreak(),
  h1("4. Proceso: Carga Masiva de Casos desde Excel"),
  p("Este proceso describe cómo el sistema procesa un archivo Excel con el formato del Ministerio de Salud Pública y Asistencia Social (MSPAS) para registrar múltiples casos de forma masiva, evitando duplicados."),
  ...imageParagraph("flow_carga_masiva.png", 350, 850, "Figura 3. Flujo de carga masiva de datos desde Excel"),
  h3("4.1 Pasos del proceso"),
  bullet("1. Un usuario con rol autorizado (administrador u operador) accede a la vista de Carga de Datos y selecciona un archivo Excel (.xlsx) con el formato MSPAS."),
  bullet("2. El frontend envía el archivo mediante POST /api/v1/upload/masivo como multipart/form-data."),
  bullet("3. Los middleware verifyToken y requireRole validan que el usuario tenga el rol autorizado para realizar cargas masivas."),
  bullet("4. Multer almacena el archivo temporalmente en el servidor."),
  bullet("5. UploadController invoca la utilidad cargaExcel.js, que abre el libro con ExcelJS y localiza la hoja de datos."),
  bullet("6. Se detecta la fila de encabezados (fila 4) y se procesan los datos a partir de la fila 5, fila por fila."),
  bullet("7. Por cada fila: si está vacía o forma parte de una tabla pivote al final de la hoja, se omite. Si el CUI o número de caso ya existe en la base de datos, se marca como duplicado e incrementa el contador correspondiente."),
  bullet("8. Si el registro es nuevo, se crean/actualizan las entidades relacionadas: NINA, CASO_EMBARAZO, HISTORIAL_EDUCATIVO y las referencias geográficas (departamento, municipio, centro educativo)."),
  bullet("9. Al finalizar el recorrido, se crea un registro en CARGA_ARCHIVO con los totales (registros totales, nuevos y duplicados)."),
  bullet("10. Se registra un evento de auditoría con acción 'carga_masiva'."),
  bullet("11. La API responde 200 (OK) con el resumen de la carga, que el frontend muestra al usuario (registros nuevos vs. duplicados)."),

  pageBreak(),
  h1("5. Proceso: Seguimiento y Actualización del Estado de un Caso"),
  p("Este proceso describe cómo los usuarios consultan los casos registrados, aplican filtros y actualizan el estado o los datos de seguimiento de un caso existente."),
  ...imageParagraph("flow_seguimiento_estado.png", 200, 850, "Figura 4. Flujo de seguimiento y actualización de estado de un caso"),
  h3("5.1 Pasos del proceso"),
  bullet("1. El usuario accede a la vista de Seguimiento, la cual solicita GET /api/v1/caso con filtros opcionales (departamento, municipio, departamental, estado, rango de fechas, texto de búsqueda)."),
  bullet("2. CasoController.ObtenerCasosFiltrados aplica los filtros recibidos y consulta CASO_EMBARAZO con sus relaciones (NINA, CENTRO_EDUCATIVO, ubicación geográfica)."),
  bullet("3. La API responde con una lista paginada de casos, que el frontend renderiza en una tabla y en los gráficos del dashboard (BarChart, LineChart, DonaChart, PieChart, GuateMap)."),
  bullet("4. Si el usuario selecciona un caso para actualizar, se abre un formulario de edición precargado con el estado actual del caso."),
  bullet("5. El usuario modifica el estado u otros datos de seguimiento y envía PUT /api/v1/caso/:id."),
  bullet("6. Los middleware verifyToken y attachUser validan la sesión."),
  bullet("7. CasoController.ActualizarCaso valida los datos recibidos; si son inválidos, responde 400 (Bad Request)."),
  bullet("8. Si los datos son válidos, se actualiza el registro en CASO_EMBARAZO y se registra un evento de auditoría con acción 'actualizar_caso'."),
  bullet("9. La API responde 200 (OK) con el caso actualizado y el frontend refresca la tabla y los gráficos."),

  pageBreak(),
  h1("6. Proceso: Consulta y Exportación de la Bitácora de Auditoría"),
  p("Este proceso describe cómo los administradores consultan el historial de acciones del sistema y exportan dicha información a Excel o PDF, incluyendo el encabezado institucional MINEDUC/SIGEC."),
  ...imageParagraph("flow_auditoria_exportacion.png", 360, 850, "Figura 5. Flujo de consulta y exportación de la bitácora de auditoría"),
  h3("6.1 Pasos del proceso"),
  bullet("1. Un usuario administrador accede a la vista de Auditoría, la cual solicita GET /api/v1/auditoria con filtros opcionales (acción, fecha desde, fecha hasta)."),
  bullet("2. Los middleware verifyToken y requireRole validan que el usuario tenga rol de administrador; de lo contrario, se responde 403 (Prohibido)."),
  bullet("3. AuditoriaController.listar consulta la tabla AUDITORIA con join a USER, aplicando los filtros y la paginación."),
  bullet("4. La API responde con los registros y la información de paginación, que el frontend muestra en una tabla con badges por tipo de acción (incluyendo inicio_sesion y cierre_sesion)."),
  bullet("5. Si el usuario elige exportar, el frontend obtiene todos los registros que cumplen los filtros activos, iterando sobre todas las páginas."),
  bullet("6. Para exportación a Excel: useExport.exportarAuditoriaExcel genera un libro con ExcelJS, incluyendo el encabezado institucional MINEDUC/SIGEC, y descarga el archivo .xlsx."),
  bullet("7. Para exportación a PDF: useExport.exportarAuditoriaPDF genera un documento con jsPDF, incluyendo el mismo encabezado institucional, y descarga el archivo .pdf."),
  bullet("8. En ambos casos, se registra un evento de auditoría con acción 'descargar_excel' o 'descargar_pdf', según corresponda."),

  h1("7. Resumen de Acciones de Auditoría"),
  p("La siguiente tabla resume todas las acciones registradas en la bitácora de auditoría del sistema, incluidas las incorporadas para el seguimiento de sesiones de usuario:"),
  table(
    ["Acción", "Origen", "Descripción"],
    [
      ["inicio_sesion", "AuthController (login)", "Se registra cuando un usuario inicia sesión correctamente."],
      ["cierre_sesion", "AuthController (logout)", "Se registra cuando un usuario cierra sesión."],
      ["crear_caso", "CasoController (RegistrarCaso)", "Se registra al crear un nuevo caso de embarazo."],
      ["actualizar_caso", "CasoController (ActualizarCaso)", "Se registra al modificar un caso existente."],
      ["crear_usuario", "UserController", "Se registra al crear un nuevo usuario del sistema."],
      ["actualizar_usuario", "UserController", "Se registra al modificar los datos de un usuario."],
      ["activar_usuario", "UserController", "Se registra al activar el acceso de un usuario."],
      ["desactivar_usuario", "UserController", "Se registra al desactivar el acceso de un usuario."],
      ["carga_masiva", "UploadController", "Se registra al completar una carga masiva desde Excel."],
      ["descargar_excel", "AuditoriaController / Frontend", "Se registra al exportar la bitácora a Excel."],
      ["descargar_pdf", "AuditoriaController / Frontend", "Se registra al exportar la bitácora a PDF."],
    ],
    [25, 30, 45]
  ),
];

writeDocx(buildDocument({ code: "DOC-03", title: "Diagramas de Flujo y Procesos", children }), "03_Diagramas_Flujo_Procesos_SIGEC.docx");
