const { h1, h2, h3, p, bullet, code, pageBreak, table, imageParagraph, titlePage, buildDocument, writeDocx } = require("./common");

const children = [
  ...titlePage({
    code: "DOC-05",
    title: "Procedimientos de Instalación, Configuración y Despliegue",
    subtitle: "SIGEC - Sistema de Información y Gestión de Casos de Embarazo en Niñas y Adolescentes",
  }),

  h1("1. Introducción"),
  p("Este documento describe los procedimientos para instalar, configurar y desplegar el sistema SIGEC, tanto en un entorno de desarrollo local como en un entorno de producción mediante contenedores Docker. Aplica a los dos componentes principales del sistema: el backend (API REST) y el frontend (SPA)."),

  h1("2. Requisitos Previos"),
  table(
    ["Requisito", "Versión / Detalle"],
    [
      ["Node.js", "20.19.0 o superior (o 22.12.0+) — definido en frontend/package.json (engines)."],
      ["npm", "Incluido con Node.js."],
      ["MySQL", "Versión 8.x, con una base de datos creada para el sistema."],
      ["Docker y Docker Compose", "Requeridos para el despliegue mediante contenedores."],
      ["Git", "Para clonar el repositorio del proyecto."],
      ["Herramientas de compilación nativa", "python3, make, g++ (necesarias para compilar dependencias nativas como bcrypt; ya incluidas en el Dockerfile del backend)."],
    ],
    [30, 70]
  ),

  pageBreak(),
  h1("3. Estructura General del Proyecto"),
  p("El repositorio se organiza en dos subproyectos independientes:"),
  bullet("backend/ : API REST en Node.js + Express 5 + Sequelize 6."),
  bullet("frontend/ : SPA en Vue 3 + Vuetify 3 + Vite."),
  bullet("nginx.conf : configuración de Nginx usada para servir el frontend en producción."),

  h1("4. Configuración de Variables de Entorno"),
  p("Ambos subproyectos utilizan archivos .env para su configuración. Estos archivos no se versionan en el repositorio (excluidos mediante .gitignore) y deben crearse manualmente en cada entorno."),

  h2("4.1 Backend (backend/.env.dev o backend/.env.prod)"),
  p("El backend carga el archivo .env.dev en desarrollo o .env.prod en producción, según el valor de NODE_ENV (ver backend/app.js y backend/server.js). Las variables requeridas son:"),
  table(
    ["Variable", "Descripción"],
    [
      ["PORT", "Puerto en el que escucha el servidor Express (por ejemplo 3000)."],
      ["NODE_ENV", "Entorno de ejecución: development, test o production. Determina qué archivo .env se carga y qué configuración de Sequelize se usa (config/config.cjs)."],
      ["CLIENT_URL", "URL del frontend permitida por la configuración CORS del backend."],
      ["DB_HOST", "Host del servidor MySQL."],
      ["DB_PORT", "Puerto del servidor MySQL (por defecto 3306)."],
      ["DB_NAME", "Nombre de la base de datos (ej. sigec)."],
      ["DB_USER", "Usuario de conexión a la base de datos."],
      ["DB_PASSWORD", "Contraseña del usuario de base de datos."],
      ["JWT_SECRET", "Clave secreta utilizada para firmar y verificar los tokens JWT (AuthController, verifyToken, attachUser)."],
      ["SEED_EXCEL_PATH", "Ruta al archivo Excel de origen utilizado por el seeder de carga inicial de casos (backend/seeders/20260611120000-cargar-excel-casos.js)."],
    ],
    [25, 75]
  ),
  p("Ejemplo de archivo backend/.env.dev:"),
  code("PORT=3000"),
  code("NODE_ENV=development"),
  code("CLIENT_URL=http://localhost:5173"),
  code("DB_HOST=127.0.0.1"),
  code("DB_PORT=3306"),
  code("DB_NAME=sigec"),
  code("DB_USER=root"),
  code("DB_PASSWORD=********"),
  code("JWT_SECRET=********"),
  code("SEED_EXCEL_PATH=./seed-data/casos.xlsx"),

  h2("4.2 Frontend (frontend/.env)"),
  table(
    ["Variable", "Descripción"],
    [
      ["VITE_API_URL", "URL base de la API consumida por el frontend mediante Axios (helpers/api.js). Ejemplo: http://localhost:3000/api/v1"],
    ],
    [25, 75]
  ),

  pageBreak(),
  h1("5. Instalación y Ejecución en Desarrollo"),
  h2("5.1 Backend"),
  bullet("1. Clonar el repositorio y posicionarse en la carpeta backend/."),
  bullet("2. Crear el archivo backend/.env.dev con las variables descritas en la sección 4.1."),
  bullet("3. Instalar dependencias:"),
  code("npm install"),
  bullet("4. Crear la base de datos en MySQL (debe coincidir con DB_NAME)."),
  bullet("5. Ejecutar las migraciones y los seeders iniciales. El script 'reset' definido en package.json revierte, vuelve a aplicar las migraciones y ejecuta todos los seeders:"),
  code("npm run reset"),
  p("Este comando ejecuta internamente:"),
  code("sequelize-cli db:migrate:undo:all && sequelize-cli db:migrate && sequelize-cli db:seed:all"),
  bullet("6. Iniciar el servidor en modo desarrollo (con recarga automática mediante nodemon):"),
  code("npm run dev"),
  bullet("7. El servidor quedará disponible en http://localhost:<PORT> (por ejemplo, http://localhost:3000), expone la API bajo el prefijo /api/v1 y ejecuta sequelize.sync() al iniciar (ver backend/server.js)."),

  h2("5.2 Frontend"),
  bullet("1. Posicionarse en la carpeta frontend/."),
  bullet("2. Crear el archivo frontend/.env con la variable VITE_API_URL apuntando a la API del backend."),
  bullet("3. Instalar dependencias:"),
  code("npm install"),
  bullet("4. Iniciar el servidor de desarrollo de Vite:"),
  code("npm run dev"),
  bullet("5. Acceder a la aplicación en la URL indicada por Vite (por defecto http://localhost:5173)."),

  pageBreak(),
  h1("6. Migraciones de Base de Datos"),
  p("Las migraciones se ubican en backend/migrations/ y se gestionan con Sequelize CLI (configuración en backend/.sequelizerc y backend/config/config.cjs). El historial de migraciones aplicadas es el siguiente:"),
  table(
    ["Migración", "Propósito"],
    [
      ["20260514221353-initial-schema.js", "Crea el esquema inicial completo: roles, usuarios, división geográfica, niñas, casos, historial educativo y cargas de archivo."],
      ["20260608000000-allow-null-cui.js", "Permite valores nulos en el campo cui de la tabla de niñas, para registros sin CUI/DPI."],
      ["20260608000001-nina-pueblo-comunidad-strings.js", "Convierte los campos pueblo y comunidad_linguistica a campos de texto libre."],
      ["20260610000000-create-auditorias.js", "Crea la tabla de auditoría para registrar la bitácora del sistema, incluyendo inicio y cierre de sesión."],
    ],
    [40, 60]
  ),
  p("Comandos útiles de Sequelize CLI (ejecutados desde backend/):"),
  code("npx sequelize-cli db:migrate            # Aplica las migraciones pendientes"),
  code("npx sequelize-cli db:migrate:undo       # Revierte la última migración"),
  code("npx sequelize-cli db:migrate:undo:all   # Revierte todas las migraciones"),
  code("npx sequelize-cli db:seed:all           # Ejecuta todos los seeders"),

  h2("6.1 Seeder de Carga Inicial desde Excel"),
  p("El seeder backend/seeders/20260611120000-cargar-excel-casos.js, junto con la utilidad backend/utils/cargaExcel.js, permite poblar la base de datos a partir de un archivo Excel con formato MSPAS. La ruta del archivo se define mediante la variable de entorno SEED_EXCEL_PATH. El proceso:"),
  bullet("Lee el archivo Excel con ExcelJS, detectando los encabezados en la fila 4 y los datos a partir de la fila 5."),
  bullet("Crea o reutiliza los registros de división geográfica (departamentos, municipios, departamentales), niñas, casos de embarazo, historial educativo y centros educativos."),
  bullet("Evita duplicados verificando la existencia previa de cada caso/niña antes de insertarlo."),
  bullet("Importa las asociaciones del modelo desde backend/models/Relations.js para garantizar que todas las relaciones (por ejemplo Departamento-Departamental) estén correctamente registradas antes de ejecutar las consultas."),

  pageBreak(),
  h1("7. Despliegue en Producción con Docker"),
  p("El despliegue en producción utiliza contenedores Docker independientes para el frontend y el backend, según se describe en el documento DOC-01 (Diagramas de Arquitectura del Sistema)."),

  h2("7.1 Backend (backend/Dockerfile)"),
  p("Imagen base: node:20-alpine. Pasos principales de la imagen:"),
  bullet("Define NODE_ENV=production desde el inicio de la imagen."),
  bullet("Instala herramientas de compilación nativa (python3, make, g++) necesarias para dependencias como bcrypt."),
  bullet("Copia package*.json e instala dependencias de producción con npm install --omit=dev."),
  bullet("Copia el resto del código fuente (respetando .dockerignore)."),
  bullet("Ejecuta el proceso con el usuario sin privilegios 'node' (no root)."),
  bullet("Expone el puerto 3000 y arranca el servidor con: node server.js"),
  p("Construcción y ejecución manual del contenedor del backend:"),
  code("docker build -t sigec-backend ./backend"),
  code("docker run -d --name sigec-backend -p 3000:3000 \\"),
  code("  --env-file ./backend/.env.prod sigec-backend"),

  h2("7.2 Frontend (frontend/Dockerfile + nginx.conf)"),
  p("La imagen del frontend se construye en dos etapas:"),
  bullet("Etapa 1 (build-stage): imagen node:20-alpine, instala dependencias con npm ci y genera el build estático de producción con npm run build (Vite), generando la carpeta dist/."),
  bullet("Etapa 2 (producción): imagen nginxinc/nginx-unprivileged:stable-alpine, copia la configuración personalizada (nginx.conf) y el contenido de dist/ generado en la etapa anterior."),
  bullet("El contenedor corre como usuario no root (uid 101), expone el puerto 8080 y define un HEALTHCHECK que verifica la disponibilidad de la aplicación cada 30 segundos."),
  p("Configuración relevante de nginx.conf:"),
  bullet("Escucha en el puerto 8080."),
  bullet("Habilita compresión Gzip para archivos de texto, CSS, JS, XML y JSON."),
  bullet("Sirve los archivos estáticos desde /usr/share/nginx/html con try_files $uri $uri/ /index.html, lo cual permite el correcto funcionamiento del enrutamiento de la SPA (Vue Router en modo history)."),

  h2("7.3 Orquestación con Docker Compose"),
  p("El archivo frontend/docker-compose.yml define el servicio del frontend:"),
  code("version: \"3.9\""),
  code("services:"),
  code("  frontend:"),
  code("    build: ."),
  code("    container_name: mockup-vite-prod"),
  code("    restart: always"),
  code("    ports:"),
  code("      - \"80:8080\""),
  p("Este servicio expone el frontend en el puerto 80 del host, redirigiendo al puerto 8080 del contenedor Nginx. Para un despliegue completo se recomienda extender este archivo (o crear uno adicional) agregando los servicios de backend y base de datos, por ejemplo:"),
  code("services:"),
  code("  backend:"),
  code("    build: ./backend"),
  code("    env_file: ./backend/.env.prod"),
  code("    ports:"),
  code("      - \"3000:3000\""),
  code("    depends_on:"),
  code("      - db"),
  code(""),
  code("  db:"),
  code("    image: mysql:8"),
  code("    environment:"),
  code("      MYSQL_DATABASE: sigec"),
  code("      MYSQL_ROOT_PASSWORD: ********"),
  code("    volumes:"),
  code("      - db_data:/var/lib/mysql"),
  code(""),
  code("  frontend:"),
  code("    build: ."),
  code("    ports:"),
  code("      - \"80:8080\""),
  code("    depends_on:"),
  code("      - backend"),

  pageBreak(),
  h1("8. Lista de Verificación Post-Despliegue"),
  bullet("La API responde correctamente en /api/v1/auth/validate-token con un token válido."),
  bullet("El frontend carga correctamente y puede autenticar usuarios contra la API configurada en VITE_API_URL."),
  bullet("Las migraciones se aplicaron correctamente y las tablas esperadas existen en la base de datos (incluyendo la tabla de auditoría)."),
  bullet("Las variables de entorno sensibles (JWT_SECRET, credenciales de base de datos) están configuradas de forma segura y no se encuentran en el control de versiones."),
  bullet("La carga masiva de archivos Excel (módulo /upload) funciona correctamente con un archivo de prueba con formato MSPAS."),
  bullet("La bitácora de auditoría registra correctamente eventos de inicio y cierre de sesión, así como las demás acciones del sistema."),
  bullet("El healthcheck del contenedor del frontend responde correctamente (HTTP 200 en el puerto 8080)."),

  h1("9. Mantenimiento y Actualizaciones"),
  bullet("Para aplicar nuevas migraciones en producción: ejecutar npx sequelize-cli db:migrate dentro del contenedor del backend (o como parte del pipeline de despliegue), evitando el uso de db:migrate:undo:all en producción."),
  bullet("Para actualizar el frontend: reconstruir la imagen Docker (docker build) tras cada cambio de código, ya que el build de Vite es estático y se genera en tiempo de construcción de la imagen."),
  bullet("Para rotar el JWT_SECRET: coordinar el cambio con un reinicio del backend, ya que invalidará todas las sesiones activas (los usuarios deberán iniciar sesión nuevamente)."),
];

writeDocx(buildDocument({ code: "DOC-05", title: "Procedimientos de Instalación, Configuración y Despliegue", children }), "05_Procedimientos_Instalacion_Configuracion_Despliegue_SIGEC.docx");
